2025-01-17T00:20:35,270 Using pip 23.2.1 from C:\Python312\Lib\site-packages\pip (python 3.12)
2025-01-17T00:20:35,273 Non-user install because site-packages writeable
2025-01-17T00:20:35,390 Created temporary directory: C:\Users\vilco\AppData\Local\Temp\pip-build-tracker-lpgukm_n
2025-01-17T00:20:35,391 Initialized build tracking at C:\Users\vilco\AppData\Local\Temp\pip-build-tracker-lpgukm_n
2025-01-17T00:20:35,392 Created build tracker: C:\Users\vilco\AppData\Local\Temp\pip-build-tracker-lpgukm_n
2025-01-17T00:20:35,393 Entered build tracker: C:\Users\vilco\AppData\Local\Temp\pip-build-tracker-lpgukm_n
2025-01-17T00:20:35,394 Created temporary directory: C:\Users\vilco\AppData\Local\Temp\pip-install-766h3wp3
2025-01-17T00:20:35,396 Created temporary directory: C:\Users\vilco\AppData\Local\Temp\pip-ephem-wheel-cache-289p9un6
2025-01-17T00:20:35,469 1 location(s) to search for versions of senior-project:
2025-01-17T00:20:35,469 * https://pypi.org/simple/senior-project/
2025-01-17T00:20:35,470 Fetching project page and analyzing links: https://pypi.org/simple/senior-project/
2025-01-17T00:20:35,471 Getting page https://pypi.org/simple/senior-project/
2025-01-17T00:20:35,472 Found index url https://pypi.org/simple/
2025-01-17T00:20:36,461 Could not fetch URL https://pypi.org/simple/senior-project/: 404 Client Error: Not Found for url: https://pypi.org/simple/senior-project/ - skipping
2025-01-17T00:20:36,462 Skipping link: not a file: https://pypi.org/simple/senior-project/
2025-01-17T00:20:36,464 Given no hashes to check 0 links for project 'senior-project': discarding no candidates
2025-01-17T00:20:36,465 ERROR: Could not find a version that satisfies the requirement senior_project (from versions: none)
2025-01-17T00:20:36,471 ERROR: No matching distribution found for senior_project
2025-01-17T00:20:36,475 Exception information:
2025-01-17T00:20:36,475 Traceback (most recent call last):
2025-01-17T00:20:36,475   File "C:\Python312\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
2025-01-17T00:20:36,475     self._add_to_criteria(self.state.criteria, r, parent=None)
2025-01-17T00:20:36,475   File "C:\Python312\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 174, in _add_to_criteria
2025-01-17T00:20:36,475     raise RequirementsConflicted(criterion)
2025-01-17T00:20:36,475 pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('senior_project')
2025-01-17T00:20:36,475 
2025-01-17T00:20:36,475 During handling of the above exception, another exception occurred:
2025-01-17T00:20:36,475 
2025-01-17T00:20:36,475 Traceback (most recent call last):
2025-01-17T00:20:36,475   File "C:\Python312\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
2025-01-17T00:20:36,475     result = self._result = resolver.resolve(
2025-01-17T00:20:36,475                             ^^^^^^^^^^^^^^^^^
2025-01-17T00:20:36,475   File "C:\Python312\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
2025-01-17T00:20:36,475     state = resolution.resolve(requirements, max_rounds=max_rounds)
2025-01-17T00:20:36,475             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-17T00:20:36,475   File "C:\Python312\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 399, in resolve
2025-01-17T00:20:36,475     raise ResolutionImpossible(e.criterion.information)
2025-01-17T00:20:36,475 pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('senior_project'), parent=None)]
2025-01-17T00:20:36,475 
2025-01-17T00:20:36,475 The above exception was the direct cause of the following exception:
2025-01-17T00:20:36,475 
2025-01-17T00:20:36,475 Traceback (most recent call last):
2025-01-17T00:20:36,475   File "C:\Python312\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
2025-01-17T00:20:36,475     status = run_func(*args)
2025-01-17T00:20:36,475              ^^^^^^^^^^^^^^^
2025-01-17T00:20:36,475   File "C:\Python312\Lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
2025-01-17T00:20:36,475     return func(self, options, args)
2025-01-17T00:20:36,475            ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-17T00:20:36,475   File "C:\Python312\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
2025-01-17T00:20:36,475     requirement_set = resolver.resolve(
2025-01-17T00:20:36,475                       ^^^^^^^^^^^^^^^^^
2025-01-17T00:20:36,475   File "C:\Python312\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 101, in resolve
2025-01-17T00:20:36,475     raise error from e
2025-01-17T00:20:36,475 pip._internal.exceptions.DistributionNotFound: No matching distribution found for senior_project
2025-01-17T00:20:36,810 Remote version of pip: 24.3.1
2025-01-17T00:20:36,810 Local version of pip:  23.2.1
2025-01-17T00:20:36,858 Was pip installed by pip? True
2025-01-17T00:20:36,858 WARNING: [present-rich] UpgradePrompt(old='23.2.1', new='24.3.1')
2025-01-17T00:20:36,865 Removed build tracker: 'C:\\Users\\vilco\\AppData\\Local\\Temp\\pip-build-tracker-lpgukm_n'
